# Generated by Django 4.1.4 on 2022-12-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='shops',
            name='photo',
            field=models.ImageField(upload_to='media/shops/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
